vich_uploader:
    db_driver: orm

    mappings:
        formation_image:
            uri_prefix: /images/formations
            upload_destination: '%kernel.project_dir%/public/images/formations'
        user_images:
            uri_prefix: :images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
        news_images:
            uri_prefix: :images/news
            upload_destination: '%kernel.project_dir%/public/images/news'